name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      OWNER: windnow
      IMAGE: tlserver
    steps:
      - uses: actions/checkout@v2

      - run: cat internal/clickhouse/main.go
      - run: docker build -t ${{ github.actor }}/$IMAGE:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER }}

      - run: docker push ${{ github.actor }}/$IMAGE:latest
