name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      OWNER: windnow
      IMAGE: tlserver
    steps:
      - uses: actions/checkout@v2

      - run: docker build -t ${{ github.actor }}/$IMAGE:latest .

#      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin

      - run: docker push ${{ github.actor }}/$IMAGE:latest
