name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      OWNER: windnow
      IMAGE: tlanalyzer-server
    steps:
      - uses: actions/checkout@v2

      - run: docker build -t ghcr.io/$IMAGE:latest .
#      - run: docker build -t ghcr.io/$OWNER/$IMAGE:latest .

      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin

      - run: docker push ghcr.io/$IMAGE:latest
#      - run: docker push ghcr.io/$OWNER/$IMAGE:latest
